version: '3.5'

volumes:
  jbpm-data:

services:
  jbpm-app:
    image: jboss/jbpm-server-full:latest
    ports:
      - 8080:8080
      - 8001:8001
    environment:
      - "JBPM_DB_DRIVER=postgres"
    volumes:
      - jbpm-data:/opt/jboss/wildfly/bin

