version: '3.5'

volumes:
  jbpm_postgres_data:
  jbpm_data:
  jbpm_user_data:

services:
  postgres:
    image: postgres:latest
    volumes:
      - jbpm_postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=jbpm"
      - "POSTGRES_USER=jbpm"
      - "POSTGRES_PASSWORD=jbpm"
    ports:
      - 5432:5432

  jbpm-app:
    image: jboss/jbpm-server-full:latest
    ports:
      - 8080:8080
      - 8001:8001
    environment:
      - "JBPM_DB_DRIVER=postgres"
      - "JBPM_DB_HOST=postgres"
    volumes:
      - jbpm_data:/opt/jboss/wildfly/bin
      - jbpm_user_data:/opt/jboss/wildfly/standalone/configuration
    depends_on:
      - postgres
